"""Add role to employee table

Revision ID: 431cdc5ab891
Revises: aa7496b1807d
Create Date: 2026-06-01 14:20:02.154885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "431cdc5ab891"
down_revision: Union[str, Sequence[str], None] = "aa7496b1807d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees",
        sa.Column(
            "role",
            sa.Enum("UI", "UX", "DEVELOPER", "HR", name="employeerole"),
            server_default="DEVELOPER",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "role")
    # ### end Alembic commands ###
