"""init

Revision ID: aa7496b1807d
Revises: 36a7fbbdca1b
Create Date: 2026-05-31 15:35:07.593948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7496b1807d'
down_revision: Union[str, Sequence[str], None] = '36a7fbbdca1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('password_hash', sa.String(), nullable=True))
    op.execute("UPDATE employees SET password_hash = 'placeholder' WHERE password_hash is NULL")
    op.alter_column('employees', "password_hash", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'password_hash')
    # ### end Alembic commands ###
